attach(Wolf_sheep3)
boxplot(`count wolves`~`count sheep`)
plot(`count wolves`)
plot(`count sheep`)
hist(`count sheep`)
hist(`count wolves`)
barplot(`count sheep`)
barplot(`count wolves`)
plot(`count wolves`~`count sheep`)
